
import { StellarEntry, TarotCard } from './types';

export const I18N = {
  en: {
    title: "ANDROMEDA ORACLE",
    subtitle: "M31 CONVERGENCE",
    labelInsight: "CORE MESSAGE",
    labelAction: "STELLAR GUIDANCE",
    labelEnergy: "ENERGY",
    dismiss: "Return to Andromeda",
    visionBtn: "ACTIVATE SENSORS",
    visionActive: "SENSORS ONLINE",
    visionStop: "OFF",
    hintReady: "Observing M31",
    hintPinch: "CAPTURING STELLAR DATA...",
    hintPalm: "GALAXY CONTROL",
    hintVictory: "RESETTING",
    preloading: "ESTABLISHING QUANTUM LINK...",
    configTitle: "ASTRO CONFIG",
    configParticles: "PARTICLE COUNT",
    configSize: "PARTICLE SCALE",
    configCoreColor: "CORE COLOR",
    configGalaxyColor: "GALAXY TINT",
    configNebula: "NEBULA INTENSITY",
    configAccretion: "ACCRETION RATE",
    configFlares: "FLARE FREQUENCY",
    statusReady: "SYSTEM READY",
    statusReading: "DECODING DESTINY",
    statusDone: "ALIGNMENT COMPLETE",
    helpTitle: "HOW TO INTERACT",
    helpDrag: "Drag to rotate the galactic view.",
    helpSensors: "Enable 'ACTIVATE SENSORS' for gesture control.",
    helpPinch: "Pinch (Index + Thumb) to capture an Oracle reading.",
    helpPalm: "Open Palm to control galaxy rotation speed.",
    helpVictory: "Victory Sign (V) to reset the constellation.",
    helpClose: "CLOSE"
  },
  cn: {
    title: "仙女座神启",
    subtitle: "M31星系之光 · 跨越两百万光年的指引",
    labelInsight: "核心意涵",
    labelAction: "行动指南",
    labelEnergy: "星能强度",
    dismiss: "回归星海",
    visionBtn: "开启探测器",
    visionActive: "感测器已上线",
    visionStop: "停用",
    hintReady: "静默观察中",
    hintPinch: "正在破译天机...",
    hintPalm: "手势控制旋转",
    hintVictory: "星系重构",
    preloading: "正在建立星际链路...",
    configTitle: "星象配置",
    configParticles: "粒子数量",
    configSize: "粒子大小",
    configCoreColor: "恒星颜色",
    configGalaxyColor: "星系色调",
    configNebula: "星云强度",
    configAccretion: "吸积速度",
    configFlares: "恒星耀斑频率",
    statusReady: "探测器就绪",
    statusReading: "正在破译天机",
    statusDone: "星象解析完成",
    helpTitle: "交互指南",
    helpDrag: "拖拽：手动旋转星系视角",
    helpSensors: "点击“开启探测器”以启用手势捕捉",
    helpPinch: "捏合（食指与拇指）：开启星象占卜",
    helpPalm: "张开手掌：控制星系旋转方向与速度",
    helpVictory: "比出剪刀手（V）：一键重置星象",
    helpClose: "关闭"
  }
};

export const TAROT_DECK: TarotCard[] = [
  { id: "fool", cn: "愚者", en: "The Fool" },
  { id: "magician", cn: "魔术师", en: "The Magician" },
  { id: "priestess", cn: "女祭司", en: "The High Priestess" },
  { id: "empress", cn: "皇后", en: "The Empress" },
  { id: "emperor", cn: "皇帝", en: "The Emperor" },
  { id: "hierophant", cn: "教皇", en: "The Hierophant" },
  { id: "lovers", cn: "恋人", en: "The Lovers" },
  { id: "chariot", cn: "战车", en: "The Chariot" },
  { id: "strength", cn: "力量", en: "Strength" },
  { id: "hermit", cn: "隐士", en: "The Hermit" },
  { id: "wheel", cn: "命运之轮", en: "Wheel of Fortune" },
  { id: "justice", cn: "正义", en: "Justice" },
  { id: "hanged", cn: "倒吊人", en: "The Hanged Man" },
  { id: "death", cn: "死神", en: "Death" },
  { id: "temperance", cn: "节制", en: "Temperance" },
  { id: "devil", cn: "恶魔", en: "The Devil" },
  { id: "tower", cn: "高塔", en: "The Tower" },
  { id: "star", cn: "星星", en: "The Star" },
  { id: "moon", cn: "月亮", en: "The Moon" },
  { id: "sun", cn: "太阳", en: "The Sun" },
  { id: "judgement", cn: "审判", en: "Judgement" },
  { id: "world", cn: "世界", en: "The World" }
];

export const STELLAR_ENGINE: Record<'cn' | 'en', Record<string, StellarEntry>> = {
  cn: {
    fool: { insight: "开始一段纯粹的旅程。", meaning: "仙女座的星尘预示着一个新的轮回，放下恐惧，向着未知的深空跃迁。", action: "勇敢迈出第一步。", energy: 5 },
    magician: { insight: "万物归于你的意志。", meaning: "你拥有操纵四大元素的星能，此刻星系正协助你将构想转化为现实。", action: "整合手头的资源。", energy: 4 },
    priestess: { insight: "静默中蕴含真相。", meaning: "在星系的阴影中，直觉比光速更锐利。倾听内心深处的潮汐波动。", action: "在孤独中寻找答案。", energy: 3 },
    empress: { insight: "丰饶的星云正在孕育。", meaning: "万物生长，生命力如同超新星般爆发，滋养着你周围的每一个灵魂。", action: "拥抱感性的力量。", energy: 5 },
    emperor: { insight: "秩序是星系的基石。", meaning: "建立你的引力场。在坚固的结构中，你的愿望将获得不朽的支撑。", action: "确立明确的界限。", energy: 4 },
    hierophant: { insight: "远古的星图指引归途。", meaning: "传统并非束缚，而是穿越星际的信标。从前人的智慧中汲取稳定的能量。", action: "寻求导师的建议。", energy: 3 },
    lovers: { insight: "灵魂的轨道在此交汇。", meaning: "两颗星辰的共振正在发生。选择比爱更重要，这是命运的分岔路口。", action: "遵循内心的共鸣。", energy: 5 },
    chariot: { insight: "意志力突破光速。", meaning: "掌控对冲的引力，向着目标全速前进。没有任何星体能阻挡你的决心。", action: "保持专注与自律。", energy: 5 },
    strength: { insight: "温柔地驯服内心的恒星。", meaning: "真正的强大源于慈悲与耐心。你不需要咆哮，就能让狂躁的能量平息。", action: "以柔克刚。", energy: 4 },
    hermit: { insight: "在虚空中点亮孤灯。", meaning: "暂时的沉寂是为了更明亮的爆发。在内向的探索中，你将发现真理。", action: "给自己留出冥想时间。", energy: 2 },
    wheel: { insight: "星旋流转，转瞬即逝。", meaning: "幸运的流星正划过你的轨道。顺应天命的起伏，在变化中寻找永恒。", action: "把握现在的机遇。", energy: 5 },
    justice: { insight: "因果的平衡不偏不倚。", meaning: "宇宙的法则在这一刻达成清算。真实的自我将被呈现在星空的天秤上。", action: "保持客观与诚实。", energy: 3 },
    hanged: { insight: "换个角度审视星图。", meaning: "停滞是为了蓄能。在牺牲中你将获得更广阔的视角，看见隐藏的维度。", action: "学会等待与臣服。", energy: 2 },
    death: { insight: "旧日的尘埃终将散去。", meaning: "不是终结，而是剧烈的转化。唯有彻底的告别，才能迎来黎明的曙光。", action: "果断斩断过去。", energy: 4 },
    temperance: { insight: "炼金术般的完美平衡。", meaning: "在极寒与极热之间，寻找生命的舒适带。融合不同的能量，创造和谐。", action: "克制极端的冲动。", energy: 4 },
    devil: { insight: "挣脱引力的幻觉。", meaning: "物质的枷锁只存在于你的执念中。看穿阴影，你原本就属于自由的星海。", action: "正视并释放欲望。", energy: 5 },
    tower: { insight: "瞬间的坍缩带来新生。", meaning: "不切实际的幻象被闪电击碎。虽然过程剧烈，但清理出的空地将更坚固。", action: "从废墟中寻找机遇。", energy: 5 },
    star: { insight: "永恒的希望在闪耀。", meaning: "在最深的黑暗中，光始终存在。你的愈合已经开始，未来是一片坦途。", action: "保持乐观与信念。", energy: 5 },
    moon: { insight: "潜意识的潮汐正在上涨。", meaning: "迷雾笼罩了轨道。不要急于行动，在朦胧中感受那些未被说出的真相。", action: "注意你的梦境暗示。", energy: 3 },
    sun: { insight: "万物在光芒中显现。", meaning: "成功与活力是此刻的主旋律。你照亮了自己，也照亮了他人。", action: "展示你的真诚面貌。", energy: 5 },
    judgement: { insight: "命运的呼唤在此回响。", meaning: "审视你的过往，做出最后的抉择。你已被赋予重生的权力，向上攀升吧。", action: "迎接全新的使命。", energy: 4 },
    world: { insight: "星系最终达成了圆满。", meaning: "一个周期的完美结束。你已与万物合一，此刻即是永恒的成就与和谐。", action: "庆祝当下的圆满。", energy: 5 }
  },
  en: {
    fool: { insight: "A pure journey begins.", meaning: "The stardust of M31 foretells a new cycle. Leap into the deep space of the unknown.", action: "Take the first step bravely.", energy: 5 },
    magician: { insight: "All rests on your will.", meaning: "You possess the stellar energy to manipulate reality. M31 is helping you manifest.", action: "Integrate your resources.", energy: 4 },
    priestess: { insight: "Silence holds the truth.", meaning: "In the galactic shadows, intuition is faster than light. Listen to your inner tides.", action: "Find answers in solitude.", energy: 3 },
    empress: { insight: "Abundant nebulae are birthing.", meaning: "Life is exploding like a supernova, nourishing every soul around you.", action: "Embrace sensual power.", energy: 5 },
    emperor: { insight: "Order is the galactic bedrock.", meaning: "Build your gravity field. In structure, your desires find eternal support.", action: "Establish clear boundaries.", energy: 4 },
    hierophant: { insight: "Ancient star charts guide home.", meaning: "Tradition is not a cage but a beacon. Draw stability from cosmic wisdom.", action: "Seek a wise mentor.", energy: 3 },
    lovers: { insight: "Soul orbits converge here.", meaning: "Resonance between stars is occurring. Choice is the bifurcation of destiny.", action: "Follow your inner vibration.", energy: 5 },
    chariot: { insight: "Willpower breaks light speed.", meaning: "Control opposing forces and accelerate. No celestial body can stop you.", action: "Stay disciplined and focused.", energy: 5 },
    strength: { insight: "Tame the inner sun gently.", meaning: "True strength comes from compassion. You don't need to roar to calm the storm.", action: "Softness overcomes hardness.", energy: 4 },
    hermit: { insight: "Light a lamp in the void.", meaning: "Silence precedes a brighter burst. In inward exploration, truth resides.", action: "Dedicate time to meditation.", energy: 2 },
    wheel: { insight: "The stellar vortex turns.", meaning: "A lucky meteor crosses your path. Flow with the divine ups and downs.", action: "Seize the present moment.", energy: 5 },
    justice: { insight: "Causality balances perfectly.", meaning: "Cosmic laws reach a settlement. Your true self is weighed by the stars.", action: "Remain objective and honest.", energy: 3 },
    hanged: { insight: "View the chart from a new angle.", meaning: "Stagnation is for recharging. Sacrifice yields a broader dimension.", action: "Learn to wait and surrender.", energy: 2 },
    death: { insight: "Dust of the past scatters.", meaning: "Not an end, but a drastic transformation. Total farewell brings the dawn.", action: "Cut ties with the past.", energy: 4 },
    temperance: { insight: "Alchemy of perfect balance.", meaning: "Find your life's comfort zone between cold and heat. Harmonize energies.", action: "Restrain extreme impulses.", energy: 4 },
    devil: { insight: "Break the illusion of gravity.", meaning: "Material chains exist only in your obsession. You belong to the free stars.", action: "Face and release desires.", energy: 5 },
    tower: { insight: "Instant collapse brings rebirth.", meaning: "Illusions are shattered by lightning. The cleared ground is more solid.", action: "Find chance in the ruins.", energy: 5 },
    star: { insight: "Eternal hope is shining.", meaning: "Light exists even in deepest dark. Your healing has begun; the path is clear.", action: "Maintain faith and hope.", energy: 5 },
    moon: { insight: "Subconscious tides are rising.", meaning: "Mist covers the orbit. Don't rush; feel the unspoken truths in the haze.", action: "Notice your dream hints.", energy: 3 },
    sun: { insight: "All manifests in the reality.", meaning: "Success and vitality are the themes. You are a beacon for others.", action: "Show your true face.", energy: 5 },
    judgement: { insight: "Destiny's call echoes now.", meaning: "Review your past and make the final choice. Rise with your right to rebirth.", action: "Embrace your new mission.", energy: 4 },
    world: { insight: "The galaxy reaches completion.", meaning: "A cycle ends perfectly. You are one with all; eternal harmony is yours.", action: "Celebrate the fulfillment.", energy: 5 }
  }
};
